"""Output stage: write CHANGELOG.md (Markdown) and changelog.json (structured).

The Markdown is Keep-a-Changelog style with a header comment linking to the
product. The JSON is the structured data for the widget Loken builds.
"""
import json
import os

HEADER_COMMENT = "<!-- Generated by Changelog Agent — changelogagent.dev -->"


def render_markdown(version, date, changes, repo_name=""):
    """Render the CHANGELOG.md text from a list of logical changes."""
    lines = [HEADER_COMMENT, ""]
    title = repo_name if repo_name else "Changelog"
    lines.append(f"# {title}")
    lines.append("")
    lines.append(f"## [{version}] - {date}")
    lines.append("")

    # order categories
    order = ["Features", "Fixes", "Improvements", "Chores"]
    by_cat = {}
    for ch in changes:
        by_cat.setdefault(ch["category"], []).append(ch)

    for cat in order:
        group = by_cat.get(cat, [])
        if not group:
            continue
        lines.append(f"### {cat}")
        lines.append("")
        for ch in group:
            note = ch.get("note", "").strip()
            if note:
                lines.append(f"- {note}")
            else:
                lines.append(f"- {ch.get('title', '')} — {ch.get('summary', '')}")
            lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def write_outputs(changes, version, date, out_dir, repo_name=""):
    """Write CHANGELOG.md and changelog.json into out_dir. Returns paths."""
    os.makedirs(out_dir, exist_ok=True)

    md_path = os.path.join(out_dir, "CHANGELOG.md")
    with open(md_path, "w", encoding="utf-8") as f:
        f.write(render_markdown(version, date, changes, repo_name))

    json_path = os.path.join(out_dir, "changelog.json")
    payload = {
        "version": version,
        "date": date,
        "repo": repo_name,
        "generated_by": "changelog-agent",
        "changes": changes,
    }
    with open(json_path, "w", encoding="utf-8") as f:
        json.dump(payload, f, indent=2, ensure_ascii=False)

    return md_path, json_path
